import { Flex } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Footer from './Footer';
import './globals.css';
import Header from './Header';
import Providers from './Providers';
import './theme-config.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} antialiased`}
		>
			<body>
				<Providers>
					<Flex direction="column" minHeight="100vh">
						<Header />
						<main className="mb-10 grow">{children}</main>
						<Footer />
					</Flex>
				</Providers>
			</body>
		</html>
	);
}
